# Generated by Django 4.1.4 on 2023-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_offer_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='order_lid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
