# Generated by Django 4.1.4 on 2023-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_list_order_lid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerprice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
